### PR TITLE
Cmake additions

### PR DESCRIPTION
**Pull request by magnific0**
- Fix that addresses https://github.com/Tudat/tudat/issues/294
- New optimization setting in DEBUG mode, to reduce memory for 32bit compilers (Windows)
- Suppress warnings during compilation from CSPICE and PaGMO.

### CODE REVIEW

**Comment by DominicDirkx** [comment]
Very good to hear!

I see that you've modified the compiler.cmake so that it _only_ includes the extra flags for a few specific versions of Mingw. You expect that the problem is something specific with these Mingw versions?

I've tested the code on my Linux machine, and all runs fine. Just to see what happens, I'm now running the tests with the:

`set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -static-libgcc -static-libstdc++")`

enabled on gcc 5.4.0. So far, so good. I'll merge this into the master in a couple of minutes.

**Comment by magnific0** [comment]
Hi Dominic,

Yes this only affects MinGW and it is somewhat known issue:

- https://stackoverflow.com/questions/7765599/strange-problems-with-c-exceptions-with-mingw

- https://github.com/Alexpux/MINGW-packages/issues/747

I do get different unit test failures now as a result of these new flags under Windows. I'll report this as soon as I have the complete picture.

**Comment by DominicDirkx** [comment]
Hi Jacco,

Ok, thanks for the update. Can you give an indication of which tests fail now? In particular: is it something that will prevent people from starting on the assignments? I've posted here:

https://github.com/Tudat/tudat/issues/294 

that the exception problem has been fixed. 

Thanks a lot for digging into this problem, and for more CMake magic!

**Comment by magnific0** [comment]
I was still looking into them. It's three failures now. All related to tolerances. So everything seems okay. I have added details to the issue.

**Comment by DominicDirkx** [comment]
Perfect! Thanks :)

**Pull request merged**
