### PR TITLE
JSON Interface

### PR DESCRIPTION
**Pull request by aleixpinardell**
Add submodules needed for the JSON Interface and MATLAB Interface.

### CODE REVIEW

**Comment by DominicDirkx** [comment]
Hi Aleix,

Two small questions about this pull request:

- There is a USE_JSON and USE_JSONCPP variable in the CMakeLists.txt. Are they both needed, and if so, what is the difference between the two?
- In the diff, the add_boost.cmake is completely removed and readded, I'm not sure if there are any changes w.r.t. the master, but considering the recent updates through pull requests #15 and #18, I'm very hesitant to change add_boost.cmake. If you need specific changes to the file, let me know. 

Cheers,

Dominic

**Comment by aleixpinardell** [comment]
USE_JSONCPP is for the jsoncpp library that was already there before I started with the JSON interface. USE_JSON is for adding the new library that I’m using (nlohmann).
I didn’t modify anything from the addboost, I just copied the file Jacco sent me because otherwise the tests weren’t working on Mac.

**Comment by DominicDirkx** [comment]
Ok, clear thanks.  Is the jsoncpp used anywhere else and Is there a point in keeping it?

**Comment by magnific0** [comment]
There might be some users who currently use it in their applications and of course there are JSON and SpiceAndJSON library expamples in the Tudat example applications.

However, I don't think having two JSON libraries makes a lot of sense and I strongly prefer the "JSON for Modern C++" library, so maybe we have to at least rewrite these two example applications. For now I don't think we should retire JSONCPP completely.

Can we make an issue for this in the tudatExampleApplications repository? I don't mind doing this, but I don't know when I'll have the time, as I think there are other Tudat tasks with higher priority at the moment.

**Comment by aleixpinardell** [comment]
I'm not sure, but I know it is mentioned in the docs:
- installation/downloadTudatBundle.rst
- tutorials/tudatFeatures/otherLibraries/index.rst
- tutorials/tudatFeatures/otherLibraries/jsoncpp.rst

And there's an example too:
- tudatBundle/tudatExampleApplications/libraryExamples/JSON

**Comment by DominicDirkx** [comment]
Ok, very clear, let's proceed with Jacco's proposal to keep them both for now, but retire the older one in the long run.

**Comment by magnific0** [comment]
Some other thoughts on pull:

- should we consider renaming tudat-matlab to tudatMatlab(Interface) it is more consistent with the current naming scheme.
- can you remove add_boost.cmake from this pull? This file is being recommitted entirely now, and it will not reflect the commit history and blame correctly.

https://i.redd.it/ghef2nzyeupz.png

**Comment by DominicDirkx** [comment]
Agreed on both :)

**Comment by magnific0** [comment]
Thanks for the updates. The changes to add_boost.cmake are still not what I meant exactly. Compare the following links to see what I mean.

V2: https://github.com/aleixpinardell/tudatBundle/blame/c766af1b6bc80e01751c0a6979379f0c01f15904/external/CMake/add_boost.cmake
V1: https://github.com/aleixpinardell/tudatBundle/blame/51fcaaee03b68fe720270fd506f99cc5f2d769ee/external/CMake/add_boost.cmake
original: https://github.com/aleixpinardell/tudatBundle/blame/f1163ef0ddf7f7a753ca3d6f66d37f0e8fc1e71c/external/CMake/add_boost.cmake

I added a PR to your fork! This aligns it with development (which you're merging into), and then bumps it to master (which contains the necessary fixes). If this doesn't solve it then let's abandon it :-).

PR: https://github.com/aleixpinardell/tudatBundle/pull/1 it should automatically show up back here if you accept.

**Comment by aleixpinardell** [comment]
I think it didn't work...
https://github.com/aleixpinardell/tudatBundle/commit/4b7a8d08cc5c1bb07b2d29c106587d94cd07bb96
It says   0 changed files  with 0 additions and 0 deletions.
And nothing was added to the commit history of the file: https://github.com/aleixpinardell/tudatBundle/commits/json/external/CMake/add_boost.cmake

**Comment by magnific0** [comment]
No indeed, I just notice this. Let's leave it as is, it's not worth the trouble :).

**Pull request closed without merging**
