### PR TITLE
Add check to prevent boost rebuilding every time.

### PR DESCRIPTION
**Pull request by magnific0**
As discussed in the following issue:
https://github.com/Tudat/tudat/issues/142

Has been tested on Windows (Boost 1.60) and Linux (Boost 1.53).

### CODE REVIEW

**Comment by magnific0** [comment]
Please hold reviewing for now. Windows is acting up on a single issue. Writing fix now.

**Comment by magnific0** [comment]
Linux preferred system libraries over local ones after the removal of FindBoost.cmake, although the directive ```Boost_NO_SYSTEM_PATHS``` was clearly specified. Also setting ```BOOST_ROOT``` solved this.
Tested on Linux and Mac OS X. Note that ```CMakeCache.txt``` should be removed. Otherwise the above still doesn't work due to caching of ```LIBRARY_SEARCH_DIRS_RELEASE```.

Just to be clear: everything works now, it is recommended to go ahead and pull in the code.

**Comment by DominicDirkx** [comment]
I've tested this on Ubuntu 16.04, with CMake 3.5.1 and it works like a charm. I'll find the time to test it on Windows and, if succesful, merge this issue.

**Comment by DominicDirkx** [comment]
Also tested on Windows, including a full re-download of Boost on the first run of CMake (manually deleted existing boost directory). Works like a charm!

For some reason the boost download from sourceforge has been painfully slow for the last few days, both from Cmake and a browser...

**Pull request merged**
